# inspiration from https://github.com/symplify/easy-coding-standard/blob/main/.github/workflows/auto_closer.yaml

name: Auto Closer PR

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            Hi, thank you for your contribution.
            Unfortunately, this repository is read-only. It's a split from our main monorepo repository.
            We'd like to kindly ask you to move the contribution there - https://github.com/hasura-extra/hasura-extra.
            We'll check it, review it and give you feed back right way.
            Thank you.