apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
data:
  HASURA_GRAPHQL_DATABASE_URL: {{ .Values.dbUrl | b64enc | quote }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.adminSecret | b64enc | quote }}
