{{- if not .Values.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
stringData:
  HASURA_GRAPHQL_DATABASE_URL: {{ tpl .Values.dbUrl $ | quote }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.adminSecret | quote }}
{{- if .Values.jwtSecret }}
  HASURA_GRAPHQL_JWT_SECRET: |-
    {{- tpl .Values.jwtSecret $ | nindent 4 }}
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: {{ .Values.unauthorizedRole | quote }}
{{- end }}
{{- with .Values.extraEnvVarsSecret }}
  {{- tpl ( . | toYaml) $ | nindent 2 }}
{{- end }}
{{- end }}
