apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
stringData:
  HASURA_GRAPHQL_DATABASE_URL: {{ .Values.dbUrl | quote }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.adminSecret | quote }}
{{- with .Values.extraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
{{- end }}