name: Helm chart tests

on:
  pull_request: ~

env:
  CT_TARGET_BRANCH: main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # ct needs history to compare
          # https://github.com/helm/chart-testing-action/issues/25
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false --debug

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.2.0

      - name: Install Postgresql
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install postgresql bitnami/postgresql \
            --version ^12.0 \
            --set auth.database=hasura \
            --set auth.postgresPassword=hasura \
            --wait \
            --wait-for-jobs

      - name: Run chart-testing (install)
        run: ct install
