# inspiration from https://github.com/symplify/symplify/blob/main/.github/workflows/split_monorepo.yaml

name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: "ramsey/composer-install@v1"

      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'src/${{ matrix.package }}'
          repository_organization: 'hasura-extra'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"

      - if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'src/${{ matrix.package }}'
          repository_organization: 'hasura-extra'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"
