# inspiration from https://github.com/symplify/symplify/blob/main/.github/workflows/unit_tests.yaml

name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request: ~

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    name: PHP 8.0 tests

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: pcov

      - uses: "ramsey/composer-install@v1"

      - run: make environment

      - uses: jtalk/url-health-check-action@v2
        name: Health check Apache
        with:
          url: http://localhost/healthz.php
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - uses: jtalk/url-health-check-action@v2
        name: Health check Hasura api client
        with:
          url: http://localhost:8081/healthz
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - uses: jtalk/url-health-check-action@v2
        name: Health check Hasura metadata
        with:
          url: http://localhost:8082/healthz
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - uses: jtalk/url-health-check-action@v2
        name: Health check Hasura GraphQLite bridge
        with:
          url: http://localhost:8083/healthz
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - uses: jtalk/url-health-check-action@v2
        name: Health check Hasura bundle
        with:
          url: http://localhost:8085/healthz
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - run: make apply-metadata

      - run: make test-all

      - uses: codecov/codecov-action@v2
        with:
          name: "phpunit-php${{ matrix.php-version }}"
          flags: phpunit
          fail_ci_if_error: true
        continue-on-error: true